//! Reading HUFF/CDIC ("huffdic") files, and the miss that used to be all a
//! broken one could say for itself.
//!
//! kindling writes PalmDOC and only PalmDOC, so everything here is about
//! files built elsewhere: `kindlegen -c2`, and every dictionary Amazon
//! publishes. The fixtures are generated by
//! `cargo run --example gen_huffdic_fixture` from the committed kindlegen
//! dictionaries, which is why the strongest assertion available is also the
//! simplest one: a huffdic file and the PalmDOC file it was made from must
//! decompress to exactly the same bytes.
//!
//! `en_huffdic_stale_index.mobi` is the shape issue #49 reported: its orth
//! index pointer was never adjusted for the HUFF and CDIC records inserted
//! ahead of the index, so anything that trusts the pointer reads a
//! compression record as an index, finds no headwords, and reports the query
//! as absent. It is constructed rather than observed - kindlegen puts its
//! compression records past the index so the index never moves - but the
//! failure it produces is exactly what a wrong index pointer looks like from
//! the outside, which is a miss with nothing to say for itself.

mod common;

use std::path::{Path, PathBuf};
use std::process::Command;

use common::{extract_text_blob, kindling_bin, parse_mobi_file};

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/huffdic")
        .join(name)
}

fn lang_fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/langs")
        .join(name)
}

fn text_of(path: &Path) -> Vec<u8> {
    let data = std::fs::read(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let parsed = parse_mobi_file(&data).expect("parse MOBI");
    extract_text_blob(&parsed, &parsed.kf7)
}

/// Runs the CLI and returns success plus stdout and stderr merged, which is
/// what most assertions here want.
fn cli(args: &[&str]) -> (bool, String) {
    let (ok, stdout, stderr) = cli_split(args);
    (ok, stdout + &stderr)
}

fn cli_split(args: &[&str]) -> (bool, String, String) {
    let out = Command::new(kindling_bin())
        .args(args)
        .output()
        .expect("spawn kindling-cli");
    (
        out.status.success(),
        String::from_utf8_lossy(&out.stdout).into_owned(),
        String::from_utf8_lossy(&out.stderr).into_owned(),
    )
}

/// The whole decoder in one assertion: the same dictionary compressed two
/// different ways has to come back identical.
#[test]
fn huffdic_text_matches_the_palmdoc_source() {
    for (huff, palmdoc) in [
        ("en_huffdic.mobi", "en/en-kindlegen.mobi"),
        ("ja_huffdic.mobi", "ja/ja-kindlegen.mobi"),
    ] {
        let decoded = text_of(&fixture(huff));
        let expected = text_of(&lang_fixture(palmdoc));
        assert!(!expected.is_empty(), "{palmdoc} produced no text");
        assert_eq!(
            decoded, expected,
            "{huff} does not decompress to the same text as {palmdoc}"
        );
        println!(
            "  \u{2713} {} decodes to the same {} bytes as {}",
            huff,
            expected.len(),
            palmdoc
        );
    }
}

/// The phrase dictionary is memoized as compressed phrases expand, so a second
/// pass over the same record runs through different code than the first.
#[test]
fn decompressing_the_same_record_twice_is_stable() {
    let path = fixture("en_huffdic.mobi");
    let data = std::fs::read(&path).unwrap();
    let parsed = parse_mobi_file(&data).expect("parse MOBI");
    let records: Vec<&[u8]> = (0..parsed.palmdb.num_records)
        .map(|i| parsed.palmdb.record(&parsed.raw, i))
        .collect();
    let model = kindling::huffcdic::Huffdic::load(&records, 0)
        .expect("huffdic tables load")
        .expect("fixture is huffdic");

    // Text record 1, minus the trailing multibyte + TBS regions.
    let raw = records[1];
    let body = &raw[..raw.len() - 2];
    let first = model.decompress(body).expect("first pass");
    let second = model.decompress(body).expect("second pass");
    assert_eq!(first, second, "memoized phrases changed the output");
    assert!(!first.is_empty());
    println!(
        "  \u{2713} record decodes to {} bytes both times ({} phrases)",
        first.len(),
        model.phrase_count()
    );
}

/// `dump` has to show that the model was understood, not merely spotted. The
/// decoded byte count matching the declared text length is what shows it.
#[test]
fn dump_reports_the_huffdic_model() {
    let path = fixture("ja_huffdic.mobi");
    let (ok, out) = cli(&["dump", path.to_str().unwrap()]);
    assert!(ok, "dump failed:\n{out}");
    assert!(
        out.contains("palmdoc.compression = 17480"),
        "fixture should be huffdic:\n{out}"
    );
    let text_length = out
        .lines()
        .find_map(|l| l.strip_prefix("palmdoc.text_length = "))
        .expect("dump should report text_length");
    assert!(
        out.contains(&format!("section0.huffdic.text_bytes = {text_length}")),
        "decoded length should match the declared text length:\n{out}"
    );
    assert!(out.contains("section0.huffdic.phrases = "), "{out}");
    assert!(out.contains("section0.huffdic.cdic_records = "), "{out}");
    println!("  \u{2713} dump decodes all {text_length} declared text bytes");
}

#[test]
fn lookup_resolves_in_a_huffdic_dictionary() {
    let path = fixture("en_huffdic.mobi");
    let (ok, out) = cli(&["lookup", path.to_str().unwrap(), "book"]);
    assert!(ok, "lookup should resolve:\n{out}");
    assert!(out.contains("resolves"), "{out}");
    assert!(
        out.contains("HUFF/CDIC"),
        "a huffdic file should say so, so a miss is not blamed on it:\n{out}"
    );
    println!("  \u{2713} huffdic dictionary resolves a headword and names its compression");
}

/// Issue #49: a dictionary whose orth index pointer was left behind still has
/// its index, and every query in it used to miss.
#[test]
fn lookup_recovers_a_stale_orth_index_pointer() {
    let stale = fixture("en_huffdic_stale_index.mobi");
    let (ok, out) = cli(&["lookup", stale.to_str().unwrap(), "book"]);
    assert!(ok, "stale-pointer dictionary should still resolve:\n{out}");
    assert!(out.contains("resolves"), "{out}");
    assert!(
        out.contains("MOBI header names record"),
        "the stale pointer should be reported, not silently worked around:\n{out}"
    );

    // Same headword, same answer as the file whose pointer is right.
    let healthy = fixture("en_huffdic.mobi");
    let (_, good) = cli(&["lookup", healthy.to_str().unwrap(), "book"]);
    let position = |s: &str| {
        s.lines()
            .find_map(|l| l.rsplit_once("text position ").map(|(_, p)| p.to_string()))
    };
    assert_eq!(
        position(&out),
        position(&good),
        "recovered index should resolve to the same text position"
    );
    println!("  \u{2713} stale orth index pointer is recovered and reported");
}

#[test]
fn dump_flags_a_stale_orth_index_pointer() {
    let (ok, out) = cli(&[
        "dump",
        fixture("en_huffdic_stale_index.mobi").to_str().unwrap(),
    ]);
    assert!(ok, "dump failed:\n{out}");
    assert!(
        out.contains("section0.orth_index_mismatch"),
        "dump should flag the mismatch:\n{out}"
    );

    let (ok, good) = cli(&["dump", fixture("en_huffdic.mobi").to_str().unwrap()]);
    assert!(ok, "dump failed:\n{good}");
    assert!(
        !good.contains("orth_index_mismatch"),
        "a healthy file should not be flagged:\n{good}"
    );
    println!("  \u{2713} dump flags the stale pointer and leaves the healthy file alone");
}

/// A miss has to say which kind of miss it is. A book has no index to search;
/// a dictionary has one that simply did not hold the word.
#[test]
fn a_miss_says_why_it_missed() {
    let dict = fixture("en_huffdic.mobi");
    let (ok, out) = cli(&["lookup", dict.to_str().unwrap(), "zzzznotaword"]);
    assert!(!ok, "a miss should exit non-zero:\n{out}");
    assert!(
        out.contains("orth index at record") && out.contains("headwords"),
        "a dictionary miss should report the index it searched:\n{out}"
    );

    let book = parity_book();
    let (ok, out) = cli(&["lookup", book.to_str().unwrap(), "alpha"]);
    assert!(!ok, "a book has nothing to resolve:\n{out}");
    assert!(
        out.contains("no dictionary index"),
        "a book should be reported as having no index at all:\n{out}"
    );
    println!("  \u{2713} an absent headword and an absent index read differently");
}

/// The subcommand is documented as a scriptable assertion, so the notes must
/// not end up in whatever is reading its output.
#[test]
fn notes_go_to_stderr_and_leave_one_line_on_stdout() {
    let stale = fixture("en_huffdic_stale_index.mobi");
    let (ok, stdout, stderr) = cli_split(&["lookup", stale.to_str().unwrap(), "book"]);
    assert!(ok, "should resolve:\n{stdout}{stderr}");
    assert_eq!(
        stdout.lines().count(),
        1,
        "stdout should be exactly the result line, got:\n{stdout}"
    );
    assert!(stdout.contains("resolves"), "{stdout}");
    assert!(stderr.contains("HUFF/CDIC"), "{stderr}");
    assert!(stderr.contains("MOBI header names record"), "{stderr}");
    println!("  \u{2713} result on stdout, both notes on stderr");
}

fn parity_book() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/parity/simple_book/kindlegen_reference.mobi")
}
