#!/usr/bin/env python3
"""Generate per-language dictionary fixtures and a test book.

For each language with a data/<lang>.tsv (headword<TAB>gloss per line) this
writes a dictionary source (OPF + content + cover + ncx + about page) and a
sideloadable test book under <lang>/, then builds three artifacts:

    <lang>/<lang>-kindling.mobi   built with kindling   (the tool under test)
    <lang>/<lang>-kindlegen.mobi  built with kindlegen  (the reference)
    <lang>/<lang>-book.mobi       a short book listing every headword to tap

The built dictionaries are committed so the parity tests run without
kindlegen, and so the dicts + book can be sideloaded for on-device checks.

Usage:
    KINDLEGEN=/path/to/kindlegen KINDLING=/path/to/kindling-cli \\
        python3 generate.py [lang ...]

With no language arguments, every data/*.tsv is generated. kindlegen and
kindling are optional; missing tools just skip that build.
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")
KINDLEGEN = os.environ.get("KINDLEGEN")
KINDLING = os.environ.get("KINDLING")

# Languages routed through kindling's generated-ORDT (per-character) path.
GENERATED_ORDT = {"ja", "zh", "ko", "ar"}
# Right-to-left scripts.
RTL = {"ar", "he", "fa", "ur"}

TITLES = {
    "el": "Greek", "en": "English", "fr": "French", "ru": "Russian",
    "tr": "Turkish", "ja": "Japanese", "zh": "Chinese", "ko": "Korean",
    "ar": "Arabic",
}


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def read_entries(lang):
    out = []
    with open(os.path.join(DATA, f"{lang}.tsv"), encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or "\t" not in line:
                continue
            w, g = line.split("\t", 1)
            out.append((w, g))
    # dedup preserving first occurrence (document order matters for ORDT)
    seen, ents = set(), []
    for w, g in out:
        if w in seen:
            continue
        seen.add(w)
        ents.append((w, g))
    return ents


def write_cover(path, lang):
    from PIL import Image, ImageDraw
    img = Image.new("RGB", (600, 800), (28, 52, 92))
    d = ImageDraw.Draw(img)
    d.text((40, 360), f"Kindling test\n{TITLES.get(lang, lang)} dictionary", fill=(255, 255, 255))
    img.save(path, "JPEG", quality=85)


def write_dict_source(d, lang, ents):
    rtl = lang in RTL
    dir_attr = ' dir="rtl"' if rtl else ""
    body = []
    for w, g in ents:
        body.append(
            '<idx:entry name="default" scriptable="yes">'
            f'<idx:orth value="{esc(w)}"><b>{esc(w)}</b></idx:orth>'
            f"<p>{esc(g)}</p></idx:entry><mbp:pagebreak/>"
        )
    html = (
        '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE html>\n'
        '<html xmlns="http://www.w3.org/1999/xhtml" '
        'xmlns:idx="http://www.mobipocket.com/idx" '
        'xmlns:mbp="http://www.mobipocket.com" '
        f'xml:lang="{lang}" lang="{lang}"{dir_attr}>\n'
        '<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>'
        f"<title>Kindling {TITLES.get(lang, lang)} Test Dictionary</title></head>\n"
        "<body><mbp:frameset>\n" + "\n".join(body) + "\n</mbp:frameset></body></html>\n"
    )
    open(os.path.join(d, "content.html"), "w", encoding="utf-8").write(html)

    usage = (
        '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE html>\n'
        '<html xmlns="http://www.w3.org/1999/xhtml"><head>'
        '<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>'
        "<title>About</title></head><body>"
        f"<h1>Kindling {TITLES.get(lang, lang)} Test Dictionary</h1>"
        f"<p>{TITLES.get(lang, lang)} to English test dictionary built with kindling "
        "to verify on-device lookup. Generated by tests/fixtures/langs/generate.py.</p>"
        "</body></html>\n"
    )
    open(os.path.join(d, "usage.html"), "w", encoding="utf-8").write(usage)

    uid = f"KindlingTestDict-{lang}"
    ncx = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1" xml:lang="en">\n'
        f'<head><meta name="dtb:uid" content="{uid}"/>'
        '<meta name="dtb:depth" content="1"/><meta name="dtb:totalPageCount" content="0"/>'
        '<meta name="dtb:maxPageNumber" content="0"/></head>\n'
        f"<docTitle><text>Kindling {TITLES.get(lang, lang)} Test Dictionary</text></docTitle>\n"
        '<navMap><navPoint id="np1" playOrder="1"><navLabel><text>About</text></navLabel>'
        '<content src="usage.html"/></navPoint></navMap>\n</ncx>\n'
    )
    open(os.path.join(d, "toc.ncx"), "w", encoding="utf-8").write(ncx)

    write_cover(os.path.join(d, "cover.jpg"), lang)

    opf = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<package version="2.0" xmlns="http://www.idpf.org/2007/opf" unique-identifier="BookId">\n'
        '<metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">\n'
        f"<dc:title>Kindling {TITLES.get(lang, lang)} Test Dictionary</dc:title>\n"
        '<dc:creator opf:role="aut">Kindling</dc:creator>\n'
        f"<dc:language>{lang}</dc:language>\n"
        f"<dc:identifier id=\"BookId\">{uid}</dc:identifier>\n"
        '<meta name="cover" content="cimage"/>\n'
        f"<x-metadata>\n<DictionaryInLanguage>{lang}</DictionaryInLanguage>\n"
        "<DictionaryOutLanguage>en</DictionaryOutLanguage>\n"
        "<DefaultLookupIndex>default</DefaultLookupIndex>\n</x-metadata>\n"
        "</metadata>\n<manifest>\n"
        '<item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>\n'
        '<item id="cimage" href="cover.jpg" media-type="image/jpeg" properties="coverimage"/>\n'
        '<item id="usage" href="usage.html" media-type="application/xhtml+xml"/>\n'
        '<item id="content" href="content.html" media-type="application/xhtml+xml"/>\n'
        '</manifest>\n<spine toc="ncx"><itemref idref="usage"/><itemref idref="content"/></spine>\n'
        '<guide><reference type="index" title="Dictionary" href="content.html"/>'
        '<reference type="toc" title="About" href="usage.html"/></guide>\n'
        "</package>\n"
    )
    opf_path = os.path.join(d, "dict.opf")
    open(opf_path, "w", encoding="utf-8").write(opf)
    return opf_path


def write_book_source(d, lang, ents):
    rtl = lang in RTL
    dir_attr = ' dir="rtl"' if rtl else ""
    rows = ["<h1>Dictionary lookup test</h1>",
            "<p>Long-press each word; the gloss is on the line below it.</p>", "<hr/>"]
    for w, g in ents:
        rows.append(f"<p>{esc(w)}</p>")
        rows.append(f"<p>= {esc(g)}</p>")
    html = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" '
        '"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">\n'
        f'<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="{lang}" lang="{lang}"{dir_attr}>\n'
        '<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>'
        f"<title>Kindling {TITLES.get(lang, lang)} Lookup Test</title></head>\n"
        "<body>\n" + "\n".join(rows) + "\n</body></html>\n"
    )
    open(os.path.join(d, "book.html"), "w", encoding="utf-8").write(html)
    opf = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<package version="2.0" xmlns="http://www.idpf.org/2007/opf" unique-identifier="BookId">\n'
        '<metadata xmlns:dc="http://purl.org/dc/elements/1.1/">\n'
        f"<dc:title>Kindling {TITLES.get(lang, lang)} Lookup Test</dc:title>\n"
        f"<dc:language>{lang}</dc:language>\n<dc:creator>Kindling</dc:creator>\n"
        f"<dc:identifier id=\"BookId\">KindlingLookupTest-{lang}</dc:identifier>\n"
        "</metadata>\n<manifest>\n"
        '<item id="content" href="book.html" media-type="application/xhtml+xml"/>\n'
        '</manifest>\n<spine><itemref idref="content"/></spine>\n</package>\n'
    )
    opf_path = os.path.join(d, "book.opf")
    open(opf_path, "w", encoding="utf-8").write(opf)
    return opf_path


def build(tool, opf, out, label):
    if not tool:
        print(f"    [skip {label}: tool not set]")
        return False
    try:
        if "kindlegen" in os.path.basename(tool).lower():
            # kindlegen writes next to the opf; -o is a bare filename.
            name = os.path.basename(out)
            subprocess.run([tool, opf, "-o", name], cwd=os.path.dirname(opf),
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            built = os.path.join(os.path.dirname(opf), name)
        else:
            subprocess.run([tool, "build", opf, "-o", out, "--no-validate"],
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            built = out
        if os.path.exists(built):
            if built != out:
                os.replace(built, out)
            print(f"    {label}: {os.path.basename(out)} ({os.path.getsize(out)} bytes)")
            return True
    except Exception as e:
        print(f"    [error {label}: {e}]")
    print(f"    [{label}: build produced no output]")
    return False


def main():
    langs = sys.argv[1:] or sorted(
        f[:-4] for f in os.listdir(DATA) if f.endswith(".tsv")
    )
    for lang in langs:
        ents = read_entries(lang)
        d = os.path.join(HERE, lang)
        src = os.path.join(d, "src")
        os.makedirs(src, exist_ok=True)
        print(f"{lang}: {len(ents)} entries  ({'per-character' if lang in GENERATED_ORDT else 'utf-16'})")
        dict_opf = write_dict_source(src, lang, ents)
        book_opf = write_book_source(src, lang, ents)
        build(KINDLING, dict_opf, os.path.join(d, f"{lang}-kindling.mobi"), "kindling dict")
        build(KINDLEGEN, dict_opf, os.path.join(d, f"{lang}-kindlegen.mobi"), "kindlegen dict")
        build(KINDLEGEN, book_opf, os.path.join(d, f"{lang}-book.mobi"), "test book")


if __name__ == "__main__":
    main()
